server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /auth { proxy_pass http://api:8000; }
    location /fetch-emails { proxy_pass http://api:8000; }
    location /filter-emails { proxy_pass http://api:8000; }
    location /emails { proxy_pass http://api:8000; }
    location /get-categories { proxy_pass http://api:8000; }
    location /rules { proxy_pass http://api:8000; }
    location /health { proxy_pass http://api:8000; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
